# -*- coding: utf-8 -*-
"""BEACNomics Cost Curve

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16OxdCtJCTVeuZxVlYWs4XumJOiJZvvZP

Welcome to the BEACNomics Cost Curve Dynamic Model! Below, by inputting values such as electricity price and emission factors, you can change the BEACNomics Cost Curve to reflect true abatement costs and potentials depending on the region of the world you're in.

All values that can be changed will be marked with a comment. Current values are given through basic assumptions and Virginia prices.
"""

import numpy as np
import matplotlib.pyplot as plt

facility_capacity = 18
annual_energy = facility_capacity * 8760

elec_price = 90.73        # retail electricity price ($) per megawatt-hour; change value
emission_factor = 0.350   # grid emission factor (tCO2e/MWh); change value

# Hot/Cold Aisle Containment

aisle_containment_width = 0.2 * annual_energy * emission_factor
aisle_containment_cost = - 0.2 * annual_energy * elec_price
aisle_containment_height = aisle_containment_cost / aisle_containment_width

# Raising Temperature Setpoint

temp_difference = 10    # difference in temperature setpoint (F); change value

temperature_width = 0.045 * temp_difference * annual_energy * emission_factor
temperature_cost = - 0.045 * temp_difference * annual_energy * elec_price
temperature_height = temperature_cost / temperature_width

# Server Virtualization

virtualization_width = 0.47 * annual_energy * emission_factor
virtualization_cost = 2600 * (900/6) - 0.47 * annual_energy * elec_price
virtualization_height = virtualization_cost / virtualization_width

# AI Cooling Optimization

vigilent_width = 26000
vigilent_height = -141

# Renewable Energy Procurement - Wind & Solar PPA

ppa_share = 0.20    # share of energy realistically coming from one renewable source; change value
wind_price = 65     # regional market price of wind energy ppa ($/MWh); change value
solar_price = 90    # regional market price of solar energy ppa ($/MWh); change value

wind_ppa_width = ppa_share * annual_energy * emission_factor
wind_ppa_annual_savings = ppa_share * annual_energy * (elec_price - wind_price)
wind_ppa_annualized_capex = (1500 * facility_capacity * 1000 * ppa_share) / 15
wind_ppa_om = 40 * facility_capacity * 1000 * ppa_share
wind_ppa_cost = -wind_ppa_annual_savings + wind_ppa_annualized_capex + wind_ppa_om
wind_ppa_height = wind_ppa_cost / wind_ppa_width

solar_ppa_width = ppa_share * annual_energy * emission_factor
solar_ppa_annual_savings = ppa_share * annual_energy * (elec_price - solar_price)
solar_ppa_annualized_capex = (1250 * facility_capacity * 1000 * ppa_share) / 15
solar_ppa_om = 12.50 * facility_capacity * 1000 * ppa_share
solar_ppa_cost = -solar_ppa_annual_savings + solar_ppa_annualized_capex + solar_ppa_om
solar_ppa_height = solar_ppa_cost / solar_ppa_width

# Carbon Offsets - ARR, REDD+, DAC

offset_limit = 1.0    # percentage of carbon emissions allowed to be offset with carbon credits; change value

arr_width = redd_width = dac_width = offset_limit * annual_energy * emission_factor
arr_height = 11
redd_height = 4
dac_height = 600

# Upgrading HVAC Infrastructure

facility_sqft = 225000    # square footage of facility (based off 18 MW); change value

hvac_width = 0.25 * annual_energy * emission_factor
hvac_cost = 25 * facility_sqft - 0.25 * annual_energy * elec_price
hvac_height = hvac_cost / hvac_width

# Efficient Hardware Upgrades

server_count = 900    # amount of servers in facility (based off 18 MW); change value

hardware_width = 0.20 * annual_energy * emission_factor
hardware_cost = 3000 * server_count - 960 * server_count
hardware_height = hardware_cost / hardware_width

# Constructing Lower PUE Data Center

old_pue = 1.57      # old data center PUE; change value
new_pue = 1.20      # new data center PUE; change value

new_dc_energy = annual_energy * (new_pue / old_pue)
lower_pue_width = (annual_energy - new_dc_energy) * emission_factor
lower_pue_annualized_capex = (12_000_000 * facility_capacity) / 20
lower_pue_savings = (annual_energy - new_dc_energy) * elec_price
lower_pue_cost = lower_pue_annualized_capex - lower_pue_savings
lower_pue_height = lower_pue_cost / lower_pue_width

# Liquid Cooling

liquid_cooling_lifespan = 5    # lifespan of liquid cooling system (years); change value

liquid_cooling_width = 0.18 * annual_energy * emission_factor
liquid_cooling_annualized_capex = (600 * facility_capacity * 1000) / liquid_cooling_lifespan
liquid_cooling_savings = 0.15 * annual_energy * elec_price
liquid_cooling_cost = liquid_cooling_annualized_capex - liquid_cooling_savings
liquid_cooling_height = liquid_cooling_cost / liquid_cooling_width

data = [
    ("Hot/Cold Aisle Containment",   aisle_containment_height,  aisle_containment_width, "most"),
    ("Raising Temperature Setpoint", temperature_height,  temperature_width, "most"),
    ("Server Virtualization",        virtualization_height,  virtualization_width, "medium"),
    ("AI Cooling Optimization",      vigilent_height,  vigilent_width, "most"),
    ("Wind Energy PPA",              wind_ppa_height,  wind_ppa_width, "least"),
    ("Carbon Offsets - REDD+",       redd_height,  redd_width, "most"),
    ("Carbon Offsets - ARR",         arr_height,  arr_width, "most"),
    ("Solar Energy PPA",             solar_ppa_height,  solar_ppa_width, "least"),
    ("Upgrading HVAC Infrastructure",  hvac_height,  hvac_width, "medium"),
    ("Efficient Hardware Upgrades",    hardware_height,  hardware_width, "medium"),
    ("Lower PUE Data Center",        lower_pue_height,  lower_pue_width, "least"),
    ("Carbon Offsets - DAC",         dac_height,  dac_width, "most"),
    ("Liquid Cooling",               liquid_cooling_height,   liquid_cooling_width, "medium"),
]

data.sort(key=lambda x: x[1])

fig, ax = plt.subplots()

# Set a default font to avoid warnings about missing fonts
plt.rcParams['font.family'] = 'DejaVu Sans'

x = 0
centers = []
gap_size = 500 # Revert gap size to 500
for label, cost, potential, convenience in data:

    if convenience == "most":
      color = "#1075e8ff"
    elif convenience == "medium":
      color = "#88b4f2ff"
    else:
      color = "#d7e7f8ff"

    # Plot the bar with its original potential width
    ax.bar(x, cost, width=potential, align='edge', color = color)
    # Calculate the center of the current bar
    centers.append(x + potential / 2)
    # Move the starting point for the next bar by potential + gap
    x += potential + gap_size

ax.set_xticks(centers)
ax.set_xticklabels([d[0] for d in data], rotation=45, ha='right')

plt.tight_layout()
plt.show()

